name: Update summaries

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate summaries
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FEED_URL: ${{ vars.FEED_URL }}
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}
          MAX_ITEMS: ${{ vars.MAX_ITEMS }}
        run: |
          python generate_summaries.py

      - name: Commit & push JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add news-data.json news-history.json
          git commit -m "auto: refresh summaries $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
